DELETE FROM entries;
DELETE FROM telementanalysis;
DELETE FROM strategies_timeframes;
DELETE FROM strategies;
DELETE FROM tanalysis;
DELETE FROM telements;
DELETE FROM pairs;
DELETE FROM users;
DELETE FROM commnets;
